import type { Metadata } from "next";
import {ThemeProvider} from "../components/theme-provider";
import "./globals.css";
import { DM_Sans, Domine } from "next/font/google";
import HeroBanner from "@/components/landing_page/footer";
// import "./globals.css";

const dmSans = DM_Sans({
  subsets: ["latin"],
  variable: "--font-dm-sans",
});

const domine = Domine({
  subsets: ["latin"],
  variable: "--font-domine",
});
export const metadata: Metadata = {
  title: "Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${dmSans.variable} ${domine.variable}`}>
      <head></head>
      <body className="font-dm-sans">
        <ThemeProvider
          attribute="class"
          defaultTheme="dark"
          enableSystem
          disableTransitionOnChange
        >

          <main className="min-h-screen font-body">{children}</main>
          <HeroBanner />
        </ThemeProvider>
      </body>
    </html>
  );
}
